# Generated by Django 5.2.5 on 2025-08-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(choices=[('folierung', 'Fahrzeugfolierung'), ('beschriftung', 'Werbebeschriftung'), ('scheibentoenung', 'Scheibentönung'), ('sonstiges', 'Sonstiges')], max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
