# Generated by Django 5.2.6 on 2025-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel des Galerie-Bildes', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung')),
                ('image', models.ImageField(help_text='Bild hochladen', upload_to='gallery/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge (kleinere Zahlen zuerst)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Bild in Galerie anzeigen')),
            ],
            options={
                'verbose_name': 'Galerie-Bild',
                'verbose_name_plural': 'Galerie-Bilder',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
