# Generated by Django 5.2.6 on 2025-10-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('folierung', 'Fahrzeugfolierung'), ('beschriftung', 'Werbebeschriftung'), ('scheibentoenung', 'Scheibentönung'), ('sonstiges', 'Sonstiges')], default='folierung', help_text='Kategorie des Projekts', max_length=50),
        ),
    ]
